# Generated by Django 3.2.4 on 2022-04-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('runs', models.CharField(max_length=20)),
                ('wickets', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('franchise', models.CharField(max_length=100)),
            ],
        ),
    ]
